language: python
python: 3.5
env:
  global:
    - PYTHONPATH=.
    - DJANGO_SETTINGS_MODULE=test_settings
  matrix:
    - TOX_ENV=py35-django19
    - TOX_ENV=py34-django19
    - TOX_ENV=py27-django19
    - TOX_ENV=py35-django18
    - TOX_ENV=py34-django18
    - TOX_ENV=py33-django18
    - TOX_ENV=py32-django18
    - TOX_ENV=py27-django18
    - TOX_ENV=py34-django17
    - TOX_ENV=py33-django17
    - TOX_ENV=py32-django17
    - TOX_ENV=py27-django17
    - TOX_ENV=coverage
    - TOX_ENV=flake8
install:
 - pip install tox coveralls
script:
  - tox -e $TOX_ENV
after_success:
  coveralls
