language: python
python:
 - "2.6"
 - "2.7"
 - "3.2"
 - "3.3"
 - "3.4"
env:
  global:
    - PYTHONPATH=.
    - DJANGO_SETTINGS_MODULE=test_settings
  matrix:
   - DJANGO_VERSION=1.4
   - DJANGO_VERSION=1.5
   - DJANGO_VERSION=1.6
   - DJANGO_VERSION=1.7
   - DJANGO_VERSION=1.8a1
matrix:
  exclude:
    - python: "3.2"
      env: DJANGO_VERSION=1.4
    - python: "3.3"
      env: DJANGO_VERSION=1.4
    - python: "3.4"
      env: DJANGO_VERSION=1.4
    - python: "3.4"
      env: DJANGO_VERSION=1.5
    - python: "3.4"
      env: DJANGO_VERSION=1.6
    - python: "2.6"
      env: DJANGO_VERSION=1.7
    - python: "2.6"
      env: DJANGO_VERSION=1.8a1
install:
 - pip install -q "Django>=${DJANGO_VERSION},<${DJANGO_VERSION}.99"
 - pip install -q South==1.0 coverage flake8
 - pip install coveralls
script:
  - django-admin.py syncdb --noinput
  - django-admin.py migrate --noinput
  - coverage run --source=logentry_admin `which django-admin.py` test logentry_admin
  - coverage report --show-missing --fail-under=90
  - flake8 logentry_admin
after_success:
  coveralls
