language: python
env:
    - TOX_ENV=py34-django110
    - TOX_ENV=py34-django19
    - TOX_ENV=py27-django110
    - TOX_ENV=py27-django19
    - TOX_ENV=py34-django18
    - TOX_ENV=py27-django18
    - TOX_ENV=py34-django17
    - TOX_ENV=py27-django17
    - TOX_ENV=flake8
matrix:
  include:
    - python: 3.5
      env:
        - TOX_ENV=py35-django111
    - python: 3.5
      env:
        - TOX_ENV=py35-django110
    - python: 3.5
      env:
        - TOX_ENV=py35-django19
    - python: 3.5
      env:
        - TOX_ENV=py35-django18
install:
  - pip install tox coveralls
script:
  - tox -e $TOX_ENV
after_success:
  coveralls
